import { FlatList, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { ChevronRight, Folder, Monitor, MoreHorizontal, Plus, RefreshCw, Search, Settings2, X } from 'lucide-react-native';
import type { RelayView } from './relay';
import { c, s } from './styles';

export type DirectoryRow = { type: 'section'; id: string; title: string } | { type: 'project'; id: string; name: string; count: number; expanded: boolean } | { type: 'thread'; id: string; title: string; active: boolean; nested: boolean };
type Props = { view: RelayView; deviceId: string; threadId: string; rows: DirectoryRow[]; search: string; wide: boolean; managing: boolean; paddingTop: number; paddingBottom: number; setSearch: (value: string) => void; selectDevice: (id: string) => void; selectThread: (id: string) => void; toggleProject: (id: string) => void; createThread: (id: string) => void; threadActions: (thread: { id: string; title: string }) => void; close: () => void; settings: () => void; refresh: () => void };
export function Directory(props: Props) {
  const { view, deviceId, threadId, rows, wide } = props;
  const device = view.devices.find(item => item.id === deviceId);
  return <View style={[s.drawer, wide && s.sidebar, { paddingTop: props.paddingTop, paddingBottom: props.paddingBottom }]}>
    <View style={s.drawerHeader}><Text style={s.brand}>Codexer</Text>{!wide && <Pressable accessibilityRole="button" accessibilityLabel="关闭会话列表" onPress={props.close} style={s.iconButton}><X size={20} color={c.text} /></Pressable>}</View>
    <View style={s.search}><Search size={17} color={c.muted} /><TextInput accessibilityLabel="搜索会话" style={s.searchInput} value={props.search} onChangeText={props.setSearch} placeholder="搜索会话" placeholderTextColor={c.muted} /></View>
    <Text style={s.section}>同账号的 PC Agent</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.deviceStrip} contentContainerStyle={s.deviceStripContent}>{view.devices.map(item => <Pressable key={item.id} accessibilityRole="button" onPress={() => props.selectDevice(item.id)} style={[s.deviceTab, deviceId === item.id && s.deviceSelected]}><Monitor size={16} color={deviceId === item.id ? c.accent : c.muted} /><Text style={[s.deviceText, deviceId === item.id && s.deviceTextSelected]} numberOfLines={1}>{item.name}</Text><View style={[s.dot, item.online && s.dotOnline]} /></Pressable>)}</ScrollView>
    <FlatList data={rows} keyExtractor={row => `${row.type}:${row.id}:${row.type === 'thread' ? row.nested : ''}`} style={s.list} contentContainerStyle={s.listContent} renderItem={({ item }) => item.type === 'section' ? <Text style={s.drawerSection}>{item.title}</Text> : item.type === 'project' ? <View style={s.project}><Pressable accessibilityRole="button" onPress={() => props.toggleProject(item.id)} style={s.projectToggle}><Folder size={18} color={c.text} /><Text style={s.projectName} numberOfLines={1}>{item.name}</Text><Text style={s.count}>{item.count}</Text><ChevronRight size={15} color={c.muted} style={item.expanded ? s.chevronDown : undefined} /></Pressable>{item.id !== 'unassigned' && <Pressable accessibilityRole="button" accessibilityLabel={`在${item.name}中新建会话`} disabled={props.managing || !device?.online} onPress={() => props.createThread(item.id)} style={s.iconButton}><Plus size={18} color={c.text} /></Pressable>}</View> : <View style={[s.threadRow, item.nested && s.threadNested, threadId === item.id && s.threadRowSelected]}><Pressable accessibilityRole="button" onPress={() => props.selectThread(item.id)} onLongPress={() => props.threadActions(item)} delayLongPress={450} style={s.threadSelect}><Text numberOfLines={1} style={s.threadName}>{item.title}</Text>{item.active && <View style={s.activeDot} />}</Pressable>{Platform.OS === 'web' && <Pressable accessibilityRole="button" accessibilityLabel={`管理会话 ${item.title}`} onPress={() => props.threadActions(item)} style={s.iconButton}><MoreHorizontal size={17} color={c.muted} /></Pressable>}</View>} ListEmptyComponent={<Text style={s.empty}>{view.catalogs[deviceId] ? '没有匹配的会话' : '正在读取项目与会话'}</Text>} />
    <View style={s.drawerFooter}><Text style={s.drawerStatus}>{view.phase === 'connected' ? `${view.devices.length} 台 PC Agent` : '正在重新连接'}</Text><Pressable accessibilityRole="button" accessibilityLabel="刷新设备" onPress={props.refresh} style={s.iconButton}><RefreshCw size={19} color={c.text} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel="连接设置" onPress={props.settings} style={s.iconButton}><Settings2 size={19} color={c.text} /></Pressable></View>
  </View>;
}
