import { Platform, StyleSheet } from 'react-native';

export const c = { bg: '#ffffff', surface: '#ffffff', text: '#191d1e', muted: '#687275', line: '#e8e9e9', accent: '#147bb5', soft: '#eef4f7', danger: '#b33942', code: '#f4f5f5' };

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: c.bg }, page: { flex: 1 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  appLayout: { flex: 1, flexDirection: 'row' }, sidebar: { width: 300, maxWidth: 300, borderRightWidth: 1, borderColor: c.line, backgroundColor: '#f8f9f9' },
  threadSelect: { flex: 1, minWidth: 0, minHeight: 43, flexDirection: 'row', alignItems: 'center', gap: 8 },
  desktopContent: { width: '100%', maxWidth: 900, alignSelf: 'center' },
  login: { flex: 1, justifyContent: 'center', alignSelf: 'center', width: '100%', maxWidth: 500, paddingHorizontal: 28 },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 36 },
  brandMark: { width: 42, height: 42, borderRadius: 7, backgroundColor: c.text, alignItems: 'center', justifyContent: 'center' },
  brand: { color: c.text, fontSize: 21, fontWeight: '700' }, heading: { color: c.text, fontSize: 23, fontWeight: '700', marginBottom: 27 },
  label: { color: c.text, fontSize: 13, fontWeight: '600', marginBottom: 8 },
  field: { minHeight: 47, borderWidth: 1, borderColor: c.line, borderRadius: 6, backgroundColor: c.surface, paddingHorizontal: 12, color: c.text, fontSize: 15, marginBottom: 20 },
  primary: { height: 46, borderRadius: 6, backgroundColor: c.accent, alignItems: 'center', justifyContent: 'center' },
  primaryText: { color: '#fff', fontWeight: '700', fontSize: 14 }, error: { color: c.danger, fontSize: 12, marginBottom: 9 }, disabled: { opacity: 0.4 },
  iconButton: { width: 38, height: 38, borderRadius: 6, alignItems: 'center', justifyContent: 'center' }, pressed: { backgroundColor: c.soft },
  header: { minHeight: 66, paddingHorizontal: 16, backgroundColor: c.surface, borderBottomWidth: 1, borderColor: c.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerActions: { flexDirection: 'row' }, sub: { color: c.muted, fontSize: 12, marginTop: 2 },
  section: { color: c.muted, fontSize: 12, fontWeight: '700', paddingHorizontal: 20, paddingTop: 14, paddingBottom: 9 },
  deviceStrip: { flexGrow: 0 }, deviceStripContent: { paddingHorizontal: 18, gap: 8, paddingBottom: 13 },
  deviceTab: { maxWidth: 200, height: 38, flexDirection: 'row', gap: 8, alignItems: 'center', paddingHorizontal: 11, borderWidth: 1, borderColor: c.line, borderRadius: 7, backgroundColor: c.surface },
  deviceSelected: { backgroundColor: c.soft, borderColor: c.accent }, deviceText: { color: c.text, fontSize: 13, flexShrink: 1 }, deviceTextSelected: { color: c.accent, fontWeight: '700' },
  dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#a8b3b3' }, dotOnline: { backgroundColor: '#24a66b' },
  search: { height: 42, marginHorizontal: 18, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, borderRadius: 8, backgroundColor: '#f2f3f3' },
  searchInput: { flex: 1, color: c.text, fontSize: 14, paddingVertical: 0 }, list: { flex: 1 }, listContent: { paddingBottom: 22 },
  project: { minHeight: 48, marginHorizontal: 10, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 7 },
  projectToggle: { flex: 1, minWidth: 0, minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12 },
  projectName: { flex: 1, color: c.text, fontWeight: '500', fontSize: 14 }, count: { color: c.muted, fontSize: 12 },
  threadRow: { minHeight: 43, marginHorizontal: 10, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 7 },
  threadNested: { paddingLeft: 32 }, threadRowSelected: { backgroundColor: c.soft },
  threadName: { flex: 1, color: c.text, fontSize: 14 }, activeDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: c.accent },
  empty: { color: c.muted, textAlign: 'center', fontSize: 14, padding: 30 },
  chatEmpty: { flex: 1, minHeight: 300, alignItems: 'center', justifyContent: 'center', gap: 9 },
  chatEmptyTitle: { color: c.text, fontSize: 19, fontWeight: '600' }, chatEmptySub: { color: c.muted, fontSize: 13 },
  threadHeader: { height: 60, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', backgroundColor: c.surface },
  threadHeading: { flex: 1, minWidth: 0, paddingHorizontal: 7 }, threadTitle: { color: c.text, fontSize: 15, fontWeight: '600' },
  stream: { flex: 1 }, streamContent: { paddingHorizontal: 18, paddingTop: 22, paddingBottom: 25, gap: 22 }, turn: { gap: 15 },
  message: { maxWidth: '100%' },
  userMessage: { alignSelf: 'flex-end', maxWidth: '88%', paddingHorizontal: 15, paddingTop: 11, paddingBottom: 4, borderRadius: 18, backgroundColor: '#f1f2f2' },
  agentMessage: { alignSelf: 'stretch', paddingVertical: 2 },
  fileNames: { color: c.muted, fontSize: 12, marginBottom: 8 }, imageRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 8 },
  image: { width: 116, height: 90, borderRadius: 4, backgroundColor: c.code },
  activity: { gap: 9 }, activityHead: { minHeight: 32, flexDirection: 'row', alignItems: 'center', gap: 8 },
  activityText: { color: c.muted, fontSize: 12, fontWeight: '600' }, activityCount: { flex: 1, color: c.muted, fontSize: 11 }, line: { height: 1, backgroundColor: c.line },
  rotated: { transform: [{ rotate: '180deg' }] }, commentary: { paddingHorizontal: 7, paddingVertical: 3 },
  tool: { borderWidth: 1, borderColor: c.line, borderRadius: 6, backgroundColor: c.surface },
  toolHead: { minHeight: 37, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 7 },
  toolTitle: { color: c.text, fontSize: 12, fontWeight: '700' }, toolPreview: { flex: 1, color: c.muted, fontSize: 12 }, toolTime: { color: c.muted, fontSize: 11 },
  toolBody: { borderTopWidth: 1, borderColor: c.line, padding: 9 },
  code: { fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', color: c.text, backgroundColor: c.code, fontSize: 12, lineHeight: 18, padding: 9, borderRadius: 4 },
  changes: { borderWidth: 1, borderColor: c.line, borderRadius: 5, backgroundColor: c.surface },
  changeHead: { minHeight: 39, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 7 },
  changeTitle: { flex: 1, color: c.text, fontSize: 12, fontWeight: '700' }, additions: { color: c.accent, fontSize: 12 }, deletions: { color: c.danger, fontSize: 12 },
  diff: { borderTopWidth: 1, borderColor: c.line, padding: 9, gap: 7 }, diffPath: { color: c.text, fontWeight: '700', fontSize: 12 },
  usage: { color: c.muted, fontSize: 11 }, earlier: { padding: 12, alignItems: 'center' }, earlierText: { color: c.accent, fontSize: 13 },
  request: { backgroundColor: '#fff7eb', borderWidth: 1, borderColor: '#eed9b2', borderRadius: 6, padding: 13, gap: 9, marginTop: 15 },
  requestTitle: { color: c.text, fontSize: 14, fontWeight: '700' }, requestText: { color: c.text, fontSize: 13 },
  option: { minHeight: 38, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: c.surface, borderWidth: 1, borderColor: c.line, borderRadius: 4 },
  optionSelected: { borderColor: c.accent }, decisionRow: { flexDirection: 'row', gap: 8 },
  decision: { minHeight: 38, paddingHorizontal: 14, borderWidth: 1, borderColor: c.line, borderRadius: 5, backgroundColor: c.surface, alignItems: 'center', justifyContent: 'center' },
  decisionAccept: { backgroundColor: c.accent, borderColor: c.accent }, smallPrimary: { alignSelf: 'flex-start', minHeight: 38, paddingHorizontal: 16, borderRadius: 5, backgroundColor: c.accent, justifyContent: 'center' },
  queue: { maxHeight: 110, backgroundColor: c.soft, borderTopWidth: 1, borderColor: c.line },
  queueRow: { minHeight: 40, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 7 }, queueText: { flex: 1, color: c.text, fontSize: 12 }, queueStatus: { color: c.muted, fontSize: 11 }, queueAction: { color: c.accent, fontWeight: '700', fontSize: 12 },
  composer: { marginHorizontal: 12, marginTop: 4, marginBottom: 7, paddingHorizontal: 10, paddingTop: 7, paddingBottom: 5, backgroundColor: '#f3f4f4', borderRadius: 22 },
  notice: { color: c.danger, fontSize: 12, marginBottom: 4 }, hint: { color: c.muted, fontSize: 11, marginBottom: 4 },
  composerInput: { minHeight: 42, maxHeight: 132, paddingHorizontal: 8, paddingTop: 7, color: c.text, fontSize: 16, lineHeight: 23 },
  toolbar: { minHeight: 39, flexDirection: 'row', alignItems: 'center', gap: 4 }, pill: { flexShrink: 1, maxWidth: 116, height: 31, paddingHorizontal: 5, flexDirection: 'row', alignItems: 'center', gap: 3 }, pillText: { flexShrink: 1, color: c.muted, fontSize: 11, fontWeight: '600' }, spacer: { flex: 1, minWidth: 0 },
  send: { width: 34, height: 34, borderRadius: 17, backgroundColor: c.text, alignItems: 'center', justifyContent: 'center' }, stop: { backgroundColor: c.accent },
  draftStrip: { flexGrow: 0, maxHeight: 78 }, draftImage: { flexDirection: 'row', alignItems: 'center', gap: 5, marginRight: 12 }, thumbnail: { width: 56, height: 56, borderRadius: 4 },
  backdrop: { flex: 1, backgroundColor: '#0007', justifyContent: 'flex-end' },
  drawerOverlay: { flex: 1, flexDirection: 'row', backgroundColor: '#0005' },
  drawer: { width: '86%', maxWidth: 390, backgroundColor: c.surface }, drawerScrim: { flex: 1 },
  drawerHeader: { height: 70, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  drawerSection: { color: c.text, fontSize: 13, fontWeight: '700', paddingHorizontal: 20, paddingTop: 21, paddingBottom: 9 },
  drawerFooter: { minHeight: 58, paddingHorizontal: 12, borderTopWidth: 1, borderColor: c.line, flexDirection: 'row', alignItems: 'center' },
  drawerStatus: { flex: 1, paddingLeft: 7, color: c.muted, fontSize: 12 }, chevronDown: { transform: [{ rotate: '90deg' }] },
  sheet: { backgroundColor: c.surface, borderTopLeftRadius: 8, borderTopRightRadius: 8, maxHeight: '70%', paddingBottom: 28, paddingHorizontal: 16 },
  modalHeader: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, modalTitle: { color: c.text, fontSize: 17, fontWeight: '700' },
  menuOption: { minHeight: 48, borderTopWidth: 1, borderColor: c.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  menuText: { flex: 1, color: c.text, fontSize: 14 }, dangerText: { flex: 1, color: c.danger, fontSize: 14 }, optionList: { flexGrow: 0 },
  viewer: { flex: 1, backgroundColor: '#101616' }, viewerHeader: { minHeight: 65, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, viewerTitle: { flex: 1, color: '#fff', fontSize: 14 },
  viewerClose: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, viewerImagePress: { flex: 1, overflow: 'hidden' },
});
