import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowRight, Check, CircleHelp, ExternalLink, FileDown, FolderOpen, Laptop, LogOut, PlugZap, Radio, RefreshCw, Server, Settings2, ShieldCheck, Terminal, Unplug, X } from 'lucide-react';
import type { Settings, ViewState } from '../types';
import { TitleBar } from './title-bar';
import './style.css';

const labels = { 'signed-out': '未登录', disconnected: '已断开', connecting: '正在连接', connected: '已连接', reconnecting: '正在重连' };
const diagnostics: Record<string, string> = { 'relay-connected': '已连接服务器', 'remote-paused': '远程连接已暂停', 'account-login-succeeded': '账号登录成功', 'account-logged-out': '已退出账号', 'relay-unavailable': '服务器暂时不可达', 'codex-binary-found': '已找到 Codex 运行程序', 'codex-binary-not-found': '未找到 Codex 程序，请在设置中选择路径', 'headless-app-server-unavailable': 'Codex 运行服务不可用，请检查安装及官方登录状态', 'catalog-refresh-failed': '无法更新本机会话目录', 'account-session-expired-login-again': '会话过期，请重新登录', 'account-session-ended-login-again': '账号登录已被撤销', 'agent-connection-replaced': '连接被其他实例替换', 'console-ready': '控制台已就绪', 'agent-started': '本机服务已启动', 'settings-saved': '设置已保存', 'worker-exited': '本机服务已退出', 'logout-server-unreachable': '已清除本机登录，服务器注销暂未确认' };
Object.assign(diagnostics, { 'relay-rejected-invalid-message': '服务器拒绝消息格式，已暂停重连', 'relay-rejected-invalid-device-state': '服务器拒绝设备状态，已暂停重连', 'relay-rejected-device-mismatch': '设备标识不匹配，已暂停重连', 'relay-rejected-stale-snapshot': '设备快照落后，已暂停重连', 'relay-rejected-invalid-history-request': '服务器的历史请求格式不兼容', 'relay-rejected-invalid-image-request': '服务器的图片请求格式不兼容', 'relay-rejected-invalid-command': '服务器的指令格式不兼容', 'relay-rejected-policy': '服务器拒绝连接，已暂停重连', 'relay-storage-error': '服务器保存设备状态失败，正在退避重试' });
function App() {
  const [state, setState] = useState<ViewState | null>(null), [tab, setTab] = useState<'connection' | 'settings' | 'logs'>('connection');
  const [settings, setSettings] = useState<Settings | null>(null), [password, setPassword] = useState(''), [localError, setLocalError] = useState(''), [note, setNote] = useState('');
  const [confirm, setConfirm] = useState<'disconnect' | 'logout' | null>(null);
  useEffect(() => { let active = true; void window.codexer.state().then(value => { if (active) setState(value); }); const unsubscribe = window.codexer.subscribe(setState); return () => { active = false; unsubscribe(); }; }, []);
  const serializedSettings = state ? JSON.stringify(state.settings) : '';
  useEffect(() => { if (state) setSettings(state.settings); }, [serializedSettings]);
  const run = async (action: () => Promise<unknown>) => { setLocalError(''); setNote(''); try { await action(); } catch (error) { setLocalError(error instanceof Error ? error.message.replace(/^Error invoking remote method '[^']+': Error: /, '') : '操作失败，请重试'); } };
  if (!state || !settings) return <div className="loading">正在启动 Codexer…</div>;
  const status = state.status, connected = state.phase === 'connected', dirty = JSON.stringify(settings) !== serializedSettings;
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings(current => current && ({ ...current, [key]: value }));
  const pick = (kind: 'home' | 'binary') => run(async () => { const path = await window.codexer.pick(kind); if (path) update(kind === 'home' ? 'codexHome' : 'codexBinary', path); });
  const save = () => run(async () => { await window.codexer.save(settings); setNote('设置已保存'); });
  const login = (event: React.FormEvent) => { event.preventDefault(); const value = password; setPassword(''); void run(async () => { if (dirty) await window.codexer.save(settings); await window.codexer.login(settings.username, value); }); };
  return <div className="app">
    <aside><div className="brand"><span className="brand-icon"><Terminal size={22}/></span><div>Codexer<small>PC 连接器</small></div></div>
      <nav aria-label="主导航">{([{ id: 'connection', icon: Radio, title: '连接状态', caption: '设备与远程连接' }, { id: 'settings', icon: Settings2, title: '设置', caption: '账号、设备与启动' }, { id: 'logs', icon: Activity, title: '诊断日志', caption: '连接与运行检查' }] as const).map(item => <button className={tab === item.id ? 'nav active' : 'nav'} key={item.id} onClick={() => setTab(item.id)}><item.icon size={20}/><span>{item.title}<small>{item.caption}</small></span></button>)}</nav>
      <div className="sidebar-bottom"><ShieldCheck size={18}/><span>凭据由系统安全保存<small>Windows / macOS</small></span></div><div className="version">Codexer {state.version}</div>
    </aside>
    <main><header><div><div className="eyebrow">LOCAL CONNECTOR</div><h1>{tab === 'connection' ? '连接状态' : tab === 'settings' ? '设置' : '诊断日志'}</h1><p>{tab === 'connection' ? '让控制端安全连接到这台电脑' : tab === 'settings' ? '配置设备和后台运行方式' : '检查连接情况，导出可分享的脱敏诊断'}</p></div><span className={`badge ${connected ? 'green' : ''}`}><i/>{labels[state.phase]}</span></header>
      {(localError || state.error) && <div role="alert" className="notice error">{state.error || localError}<button aria-label="打开诊断" onClick={() => setTab('logs')}>查看诊断</button></div>}{note && <div role="status" className="notice success">{note}</div>}
      {tab === 'connection' && <>
        <section className={`connection-card ${connected ? 'is-connected' : ''}`}><div className="connection-heading"><span className="eyebrow">REMOTE CONNECTION</span><span>账号会话 · 加密保存</span></div><div className="link-diagram"><div><span className="device-icon"><Laptop size={32}/></span><strong>{state.settings.deviceName}</strong><small>当前电脑</small></div><div className="link-line"><i/><span>{labels[state.phase]}</span><i/></div><div><span className="device-icon"><Server size={32}/></span><strong>Relay 服务器</strong><small>{state.settings.relayUrl || '尚未配置'}</small></div></div>
          <div className="connection-actions"><div><h2>{connected ? '远程连接已就绪' : state.phase === 'signed-out' ? '登录账号，连接这台电脑' : state.phase === 'disconnected' ? '远程连接已暂停' : '正在建立远程连接'}</h2><p>{connected ? '使用同一账号在控制端选择这台电脑。' : state.phase === 'disconnected' ? '本机任务会继续运行，连接后恢复远程控制。' : '连接器需要本机已安装并登录官方 Codex。'}</p></div>
            {state.loggedIn && <div className="buttons">{state.phase === 'disconnected' ? <button className="primary" disabled={state.busy} onClick={() => void run(() => window.codexer.connect())}><PlugZap size={17}/>连接</button> : <button disabled={state.busy} onClick={() => setConfirm('disconnect')}><Unplug size={17}/>断开</button>}<button disabled={state.busy} onClick={() => void run(() => window.codexer.reconnect())}><RefreshCw size={17}/>重连</button></div>}
          </div>
        </section>
        {(state.loggedIn || status) && <div className="metrics"><section><span>本机运行环境</span><strong>{status?.runtimeConnected ? '可用' : '等待接入'}</strong><small>{status?.runtime === 'official-desktop-ipc' ? '官方桌面 IPC' : status?.runtime === 'official-app-server' ? '官方 App Server' : '连接后检查'}</small></section><section><span>正在运行的任务</span><strong>{status?.activeTasks ?? '—'}<em>个</em></strong><small>断开后继续执行</small></section><section><span>已同步会话</span><strong>{status?.threads ?? '—'}<em>个</em></strong><small>来自本机 Codex 目录</small></section></div>}
        {!state.loggedIn ? <section><div className="section-title"><h2>账号登录</h2><span><ShieldCheck size={15}/>不保存密码</span></div><form onSubmit={login} className="login-form"><label>服务器地址<input type="url" required value={settings.relayUrl} placeholder="https://relay.example.com" onChange={event => update('relayUrl', event.target.value)}/></label><label>设备名称<input required maxLength={200} value={settings.deviceName} onChange={event => update('deviceName', event.target.value)}/></label><label>账号<input required autoComplete="username" maxLength={100} value={settings.username} onChange={event => update('username', event.target.value)}/></label><label>密码<input required type="password" autoComplete="current-password" maxLength={128} value={password} onChange={event => setPassword(event.target.value)}/></label><div className="form-footer"><span>会话失效后需要重新登录。</span><button className="primary" disabled={state.busy || !state.secureStorage} type="submit">{state.busy ? '正在处理…' : '登录并连接'}<ArrowRight size={16}/></button></div></form></section> : <section className="account-row"><div><h2>当前账号 · {state.settings.username}</h2><p>会话有效期至 {state.expiresAt ? new Date(state.expiresAt).toLocaleString() : '—'}</p></div><div className="buttons"><button onClick={() => void run(() => window.codexer.openControl())}><ExternalLink size={16}/>打开控制端</button><button disabled={state.busy} onClick={() => setConfirm('logout')}><LogOut size={16}/>退出登录</button></div></section>}
        <div className="hint"><CircleHelp size={17}/><span>关闭窗口默认进入托盘。点击“断开”会暂停重连并停止接收新的远程指令。</span></div>
      </>}
      {tab === 'settings' && <>
        <section><div className="section-title"><h2>设备与运行环境</h2><span>修改后手动连接</span></div><div className="settings-grid"><label>服务器地址<input type="url" value={settings.relayUrl} placeholder="https://relay.example.com" onChange={event => update('relayUrl', event.target.value)}/></label><label>设备名称<input maxLength={200} value={settings.deviceName} onChange={event => update('deviceName', event.target.value)}/></label><label className="wide">Codex 数据目录<div className="path-field"><input value={settings.codexHome} onChange={event => update('codexHome', event.target.value)}/><button aria-label="选择数据目录" onClick={() => void pick('home')}><FolderOpen size={17}/></button></div></label><label className="wide">Codex 程序路径<div className="path-field"><input value={settings.codexBinary} placeholder="自动查找；找不到时选择程序" onChange={event => update('codexBinary', event.target.value)}/><button aria-label="选择程序" onClick={() => void pick('binary')}><FolderOpen size={17}/></button></div></label><label>运行方式<select value={settings.runtime} onChange={event => update('runtime', event.target.value as Settings['runtime'])}><option value="auto">自动 · 优先官方桌面</option><option value="desktop">仅官方桌面 IPC</option><option value="headless">仅官方 App Server</option></select></label></div><p className="footnote">修改服务器地址或设备名称后需重新登录。有本机任务运行时，运行配置暂不能修改。</p></section>
        <section><div className="section-title"><h2>启动与后台</h2></div>{([{ key: 'openAtLogin', title: '开机启动', detail: '登录系统后启动 Codexer' }, { key: 'autoConnect', title: '启动后自动连接', detail: '使用已保存且有效的账号会话连接服务器' }, { key: 'minimizeToTray', title: '关闭窗口后留在后台', detail: '通过 Windows 托盘或 macOS 菜单栏打开控制台' }, { key: 'allowHttp', title: '允许远程 HTTP', detail: '用于内网或测试；HTTP 会明文传输账号和任务，公网请使用 HTTPS' }] as const).map(item => <label key={item.key} className="toggle-row"><span><strong>{item.title}</strong><small>{item.detail}</small></span><input type="checkbox" role="switch" checked={settings[item.key]} onChange={event => update(item.key, event.target.checked)}/></label>)}</section>
        <div className="save-bar"><span>{dirty ? '有未保存的设置' : '设置已同步'}</span><button className="primary" disabled={!dirty || state.busy} onClick={() => void save()}><Check size={16}/>保存设置</button></div>
      </>}
      {tab === 'logs' && <>
        <section><div className="section-title"><h2>运行检查</h2><button disabled={state.busy || !state.loggedIn} onClick={() => void run(() => window.codexer.reconnect())}><RefreshCw size={16}/>重新连接</button></div><div className="checks">{[{ title: '系统安全存储', ready: state.secureStorage }, { title: '账号登录', ready: state.loggedIn }, { title: 'Relay 连接', ready: connected }, { title: '本机 Codex 运行环境', ready: !!status?.runtimeConnected }].map(item => <div key={item.title}><span className={item.ready ? 'check-icon ready' : 'check-icon'}><Check size={15}/></span>{item.title}<small>{item.ready ? '通过' : '等待或需要检查'}</small></div>)}</div></section>
        <section><div className="section-title"><h2>最近诊断</h2><button onClick={() => void run(async () => { const path = await window.codexer.exportLogs(); if (path) setNote('已导出脱敏诊断'); })}><FileDown size={16}/>导出诊断</button></div><p className="footnote">仅记录诊断代码，不包含服务器地址、密码、会话凭据或任务内容。</p><div className="log-list" role="log">{state.logs.slice().reverse().map((entry, index) => <div key={`${entry.at}-${index}`}><time>{new Date(entry.at).toLocaleTimeString()}</time><span>{diagnostics[entry.code] || entry.code}</span><code>{entry.code}</code></div>)}{!state.logs.length && <p>暂无诊断记录</p>}</div></section>
      </>}
      <footer><span><i className={connected ? 'online' : ''}/>{state.settings.deviceName}</span><span>{status ? `更新于 ${new Date(status.updatedAt).toLocaleTimeString()}` : '本机服务尚未启动'}</span></footer>
    </main>
    {confirm && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><button className="close" aria-label="取消" onClick={() => setConfirm(null)}><X size={20}/></button><span className="modal-icon"><Unplug size={25}/></span><h2 id="confirm-title">{confirm === 'logout' ? '退出账号登录？' : '断开远程连接？'}</h2><p>暂停自动重连并停止接收新的远程指令。已经开始的本机任务会继续运行，待发送消息暂停执行。</p>{confirm === 'logout' && <p>本机保存的账号会话将被清除，再次连接需要登录。</p>}<div className="buttons"><button autoFocus onClick={() => setConfirm(null)}>取消</button><button className="primary" onClick={() => { const action = confirm; setConfirm(null); void run(() => action === 'logout' ? window.codexer.logout() : window.codexer.disconnect()); }}>{confirm === 'logout' ? '退出登录' : '断开连接'}</button></div></section></div>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<><TitleBar/><App/></>);
