import type { WidgetState } from './previews.js';
import { PREVIEW_RUNTIME_SOURCE } from './preview-runtime-source.js';

export const previewStyles = `
:root{color-scheme:light;--background:#fff;--foreground:#191d1e;--card:#fff;--card-foreground:#191d1e;--popover:#fff;--popover-foreground:#191d1e;--muted:#f0f3f5;--muted-foreground:#687275;--primary:#191d1e;--primary-foreground:#fff;--secondary:#f0f3f5;--secondary-foreground:#191d1e;--accent:#eef4f7;--accent-foreground:#147bb5;--destructive:#b33942;--border:#e1e7e9;--ring:#147bb5;--blue:#3478c8;--orange:#bf781c;--green:#218465;--red:#b33942;--purple:#7c59bf;--yellow:#a89526;--viz-series-1:#147bb5;--viz-series-2:#b26d27;--viz-series-3:#31806a;--viz-series-4:#8b61bc;--viz-series-5:#bc5964;--viz-series-6:#798341;--font-size-base:14px}
html,body{margin:0;padding:0;min-height:0;background:transparent;color:var(--foreground);font:400 var(--font-size-base)/1.5 system-ui,sans-serif}*{box-sizing:border-box}h1,h2,h3{font-weight:500}h1{font-size:1.6em}h2{font-size:1.35em}h3{font-size:1.1em}.card{padding:16px;border:1px solid var(--border);border-radius:12px;background:var(--card);color:var(--card-foreground)}.viz-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(180px,100%),1fr));gap:12px}.viz-row,.viz-controls,.nav{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.viz-controls{margin:12px 0}.viz-stat-value{font-size:1.7em;font-weight:500}.text-small{font-size:12px}.text-muted{color:var(--muted-foreground)}.tabular-nums{font-variant-numeric:tabular-nums}.btn,.nav-link{border:1px solid var(--border);padding:8px 12px;border-radius:8px;background:var(--background);color:var(--foreground);font:inherit;cursor:pointer}.btn-primary,.nav-link.active,[aria-pressed=true]{background:var(--primary);color:var(--primary-foreground)}.btn-ghost{background:transparent;border-color:transparent}.btn-block{width:100%}.form-label{display:grid;gap:6px}.form-control,.form-select{padding:8px 10px;border:1px solid var(--border);border-radius:7px;font:inherit;background:var(--background);color:var(--foreground);max-width:100%}.form-range{max-width:100%}.form-check{display:flex;gap:8px;align-items:center}.form-check-input{accent-color:var(--primary)}.progress{height:8px;background:var(--muted);border-radius:8px;overflow:hidden}.progress-bar{height:100%;background:var(--viz-series-1)}.viz-badge{padding:3px 8px;border-radius:20px;background:var(--accent);color:var(--accent-foreground)}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:8px;border-bottom:1px solid var(--border);text-align:left;overflow-wrap:anywhere}.table-responsive{overflow-x:auto}.text-end{text-align:right!important}.text-center{text-align:center!important}.text-nowrap{white-space:nowrap}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}[hidden]{display:none!important}svg{max-width:100%}hr{border:0;border-top:1px solid var(--border);margin:16px 0}:focus-visible{outline:2px solid var(--ring);outline-offset:2px}.viz-dotted-background{background-image:radial-gradient(var(--border) 1px,transparent 1px);background-size:16px 16px}@media(pointer:coarse){button,select,input:not([type=range]){min-height:44px}.form-control,.form-select{font-size:16px}}
`;
const assets = 'https://cdnjs.cloudflare.com https://esm.sh https://cdn.jsdelivr.net https://unpkg.com https://fonts.googleapis.com https://fonts.gstatic.com https://fonts.bunny.net';
export const previewCsp = `default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' ${assets}; style-src 'unsafe-inline' ${assets}; img-src data: blob: ${assets}; font-src data: ${assets}; media-src data: blob: ${assets}; connect-src ${assets}; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'`;
const safeJson = (value: unknown) => JSON.stringify(value).replaceAll('<', '\\u003c').replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029');

export function buildPreviewDocument(html: string, channel: string, state: WidgetState | null, network = false): string {
  const csp = network ? previewCsp.replace(/script-src /, "script-src 'self' ").replace(/style-src /, "style-src 'self' ").replace(/img-src /, "img-src 'self' ").replace(/font-src /, "font-src 'self' ").replace(/connect-src /, "connect-src 'self' ws: wss: ").replace("base-uri 'none'", "base-uri 'self'").replace("form-action 'none'", "form-action 'self'") : previewCsp;
  const head = `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="${csp}"><style>${previewStyles}</style><script>(${PREVIEW_RUNTIME_SOURCE.replaceAll('</script', '<\\/script')})(${safeJson(channel)},${safeJson(state)});</script>`;
  if (/<head(?:\s[^>]*)?>/i.test(html)) return html.replace(/<head(?:\s[^>]*)?>/i, match => match + head);
  return `<!doctype html><html><head>${head}</head><body>${html}</body></html>`;
}

/** Native WebView receives a trusted shell; untrusted content stays inside a sandboxed frame. */
export function nativePreviewShell(document: string, channel: string, remote = false): string {
  const escape = (text: string) => text.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
  return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0}iframe{display:block;width:100%;height:100%;border:0}</style></head><body><iframe id="preview" sandbox="allow-scripts allow-forms" ${remote ? 'src' : 'srcdoc'}="${escape(document)}"></iframe><script>const frame=document.getElementById('preview');const channel=${safeJson(channel)};window.addEventListener('message',e=>{if(e.source===frame.contentWindow&&e.data?.channel===channel){if(e.data.type==='height')frame.style.height=e.data.height+'px';window.ReactNativeWebView.postMessage(JSON.stringify(e.data))}});window.codexerPreviewSend=m=>frame.contentWindow.postMessage({...m,channel},'*');frame.addEventListener('load',()=>window.codexerPreviewSend({type:'initialize'}));</script></body></html>`;
}
